/* Run with Playwright available: NODE_PATH=<packages> node tests/browser.cjs.
   Start frontend on 3000 and backend on 8000 first. Uses an isolated Chrome profile. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const output = process.env.MEDCARE_TEST_OUTPUT || path.join(process.cwd(), 'test-results');
fs.mkdirSync(output, { recursive: true });
const log = [];
(async () => {
  const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.setDefaultTimeout(20000);
  const home = async () => { await page.goto(process.env.BASE_URL || 'http://localhost:3000', { waitUntil: 'networkidle' }); };
  const quiz = () => page.locator('#consultation');
  const qa = () => page.locator('#rag');
  await home();
  const appearance = await page.locator('#top p').first().evaluate(e => ({ color: getComputedStyle(e).color, font: getComputedStyle(e).fontFamily }));
  assert.notEqual(appearance.color, 'rgb(7, 17, 31)');
  assert.ok(!appearance.font.includes('Times New Roman'));
  log.push('Readable hero text and system sans-serif font: PASS');
  await quiz().getByRole('button', { name: 'Fatigue', exact: true }).click();
  await quiz().getByRole('button', { name: 'Continue', exact: true }).click();
  await quiz().getByRole('button', { name: '1-2 days', exact: true }).click();
  await quiz().getByRole('button', { name: 'Back', exact: true }).click();
  assert.equal(await quiz().getByRole('button', { name: 'Fatigue', exact: true }).getAttribute('aria-pressed'), 'true');
  await quiz().getByRole('button', { name: 'Continue', exact: true }).click();
  await quiz().getByRole('button', { name: 'Continue', exact: true }).click();
  await quiz().getByRole('button', { name: /^Mild/ }).click();
  await quiz().getByRole('button', { name: 'Continue', exact: true }).click();
  await quiz().getByRole('button', { name: 'None of these', exact: true }).click();
  await quiz().getByRole('button', { name: 'Continue', exact: true }).click();
  await quiz().getByRole('textbox', { name: 'Additional details' }).fill('I have felt tired for two days.');
  await quiz().getByRole('button', { name: 'Begin consultation', exact: true }).click();
  await quiz().getByRole('button', { name: 'About the same', exact: true }).click();
  await quiz().getByRole('button', { name: 'No, that is everything', exact: true }).click();
  await quiz().getByText('Your consultation summary', { exact: true }).waitFor();
  assert.equal(await quiz().getByRole('alert').count(), 0);
  await quiz().getByText(/LOW/).first().waitFor();
  await quiz().getByText('Follow-up answers', { exact: true }).waitFor();
  log.push('No-key quiz, back navigation, adaptive chat, auto-summary and follow-up retention: PASS');
  await page.screenshot({ path: path.join(output, 'desktop-summary.png'), fullPage: true });
  await quiz().getByRole('button', { name: 'Continue chat', exact: true }).click();
  await quiz().getByRole('textbox', { name: 'Type your response' }).fill('When should I seek care for fatigue?');
  await quiz().getByRole('button', { name: 'Send response' }).click();
  await quiz().getByRole('link', { name: /NHS: Tiredness/ }).first().waitFor();
  await quiz().getByRole('button', { name: 'View my summary' }).click();
  await quiz().getByRole('button', { name: 'Start new consultation' }).click();
  await quiz().getByRole('button', { name: 'Fatigue', exact: true }).waitFor();
  assert.equal(await quiz().getByRole('button', { name: 'Fatigue', exact: true }).getAttribute('aria-pressed'), 'false');
  log.push('Continue Chat retrieves sources; reset clears quiz state: PASS');
  await qa().getByRole('button', { name: 'How long can a cough last?', exact: true }).click();
  await qa().getByRole('link', { name: /NHS: Cough/ }).first().waitFor();
  await qa().getByText('Retrieved answer · Sources shown below', { exact: true }).waitFor();
  log.push('Standalone RAG question and visible source links: PASS');
  for (const width of [320,375,390,430,768,1024,1440]) {
    await page.setViewportSize({ width, height: 900 });
    await qa().scrollIntoViewIfNeeded();
    const dimensions = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }));
    assert.ok(dimensions.scroll <= dimensions.width, `Overflow at ${width}: ${JSON.stringify(dimensions)}`);
    const input = qa().getByRole('textbox', { name: 'Type your response' });
    await input.scrollIntoViewIfNeeded();
    const bounds = await input.boundingBox();
    assert.ok(bounds.width >= 120 && bounds.x >= 0 && bounds.x + bounds.width <= width + 1);
    if (width === 390) await page.screenshot({ path: path.join(output, 'mobile-qa.png') });
    log.push(`Viewport ${width}: no horizontal overflow and usable composer PASS`);
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await qa().getByRole('button', { name: 'Clear question history' }).click();
  await qa().getByRole('button', { name: 'What is a fever?', exact: true }).waitFor();
  await page.route('**/chat', route => route.abort('failed'));
  await qa().getByRole('button', { name: 'What is a fever?', exact: true }).click();
  await qa().getByText(/could not reach the analysis service/).waitFor();
  await page.unroute('**/chat');
  await qa().getByRole('button', { name: 'Try again', exact: true }).click();
  await qa().getByRole('link', { name: /NHS: Fever/ }).first().waitFor();
  log.push('Backend unavailable, useful error and successful retry: PASS');
  await qa().getByRole('button', { name: 'Clear question history' }).click();
  await qa().getByRole('button', { name: 'What is a fever?', exact: true }).waitFor();
  await page.route('**/chat', route => route.fulfill({ status: 200, contentType: 'application/json', body: '{}' }));
  await qa().getByRole('button', { name: 'What is a fever?', exact: true }).click();
  await qa().getByText(/invalid response/).waitFor();
  await page.unroute('**/chat');
  log.push('Malformed success payload produces safe parsing error: PASS');
  await qa().getByRole('button', { name: 'Try again', exact: true }).click();
  await qa().getByRole('link', { name: /NHS: Fever/ }).first().waitFor();
  await qa().getByRole('textbox', { name: 'Type your response' }).fill('I cannot breathe');
  await qa().getByRole('button', { name: 'Send response' }).click();
  await qa().getByRole('heading', { name: 'Urgent medical attention' }).waitFor();
  assert.equal(await qa().getByRole('textbox', { name: 'Type your response' }).isDisabled(), true);
  log.push('Free-text emergency interrupts RAG and disables further chat: PASS');
  await quiz().getByRole('button', { name: 'Chest pain', exact: true }).click();
  await quiz().getByRole('heading', { name: 'Urgent medical attention' }).waitFor();
  assert.equal(await quiz().getByRole('button', { name: 'Continue', exact: true }).count(), 0);
  log.push('Explicit warning selection interrupts quiz immediately: PASS');
  assert.deepEqual(errors, []);
  log.push('No uncaught browser exceptions: PASS');
  await browser.close();
  fs.writeFileSync(path.join(output, 'browser-results.json'), JSON.stringify(log, null, 2));
  console.log(log.join('\n'));
})().catch(error => { console.error(error); process.exit(1); });
